name: Sync settings

on:
  push:
    branches:
      - '*'

jobs:
  upload_settings:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Process and Upload Settings
        id: process_and_upload
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
        run: |
          process_directory() {
            local branch=$1
            echo "Processing $branch settings..."
            
            # Create empty array for configs
            echo "[]" > "$branch-settings.json"
            
            for file in "LiquidBounce/settings/$branch"/*; do
              if [ -f "$file" ]; then
                setting_id=$(basename "$file" | cut -f 1 -d '.')
                
                # Get file data in base64
                data=$(base64 -w 0 "$file")
                
                # Calculate checksum
                checksum=$(sha256sum "$file" | cut -d ' ' -f 1)
                
                # Get timestamp
                timestamp=$(git log -1 --format=%ai -- "$file" | cut -d ' ' -f 1,2 | tr ' ' 'T')Z
                
                # Create JSON object and append to array using jq
                jq --arg name "$setting_id" \
                   --arg data "$data" \
                   --arg checksum "$checksum" \
                   --arg timestamp "$timestamp" \
                   '. += [{
                     "name": $name,
                     "data": $data,
                     "checksum": $checksum,
                     "timestamp": $timestamp
                   }]' "$branch-settings.json" > temp.json && mv temp.json "$branch-settings.json"
              fi
            done
            
            if [ -s "$branch-settings.json" ]; then
              # Upload to API
              echo "Uploading $branch settings..."
              curl -X POST \
                -H "Authorization: $AUTHORIZATION" \
                -H "Content-Type: application/json" \
                -d @"$branch-settings.json" \
                "https://api.liquidbounce.net/api/v1/client/$branch/settings/sync"
                
              # Print the total number of settings processed
              echo "Total settings processed for $branch: $(jq length "$branch-settings.json")"
            else
              echo "No settings found for $branch"
            fi
          }
          
          # Process both nextgen and legacy in one go
          process_directory "nextgen"
          process_directory "legacy"

      - name: Upload JSON Files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: settings-payloads
          path: |
            nextgen-settings.json
            legacy-settings.json
