name: Sync settings

on:
  push:
    branches:
      - '**'

jobs:
  upload_settings:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install required tools
        run: sudo apt-get install -y coreutils

      - name: Process and Upload Settings
        id: process_and_upload
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
        run: |
          set -e

          process_directory() {
            local branch="$1"
            local safe_branch_name=$(echo "$branch" | tr '/' '-')
            echo "Processing settings for branch: $branch"

            local json_start='['
            local json_end=']'
            local json_entries=""

            for file in "LiquidBounce/settings/$branch"/*; do
              if [ -f "$file" ]; then
                local setting_id=$(basename "$file" | cut -f 1 -d '.')
                local data=$(base64 -w 0 "$file")
                local checksum=$(sha256sum "$file" | cut -d ' ' -f 1)
                local timestamp=$(git log -1 --format=%ai -- "$file" | cut -d ' ' -f 1,2 | tr ' ' 'T')Z
                local contributors=$(git log -1 --format='%an <%ae>' -- "$file")

                # Append JSON entry
                json_entries="${json_entries}{\"name\":\"${setting_id}\",\"data\":\"${data}\",\"checksum\":\"${checksum}\",\"timestamp\":\"${timestamp}\",\"contributors\":\"${contributors}\"},"
              fi
            done

            # Remove trailing comma and wrap with brackets
            json_payload="${json_start}${json_entries%,}${json_end}"
            echo "$json_payload" > "${safe_branch_name}-settings.json"
          }

          upload_settings() {
            local branch="$1"
            local safe_branch_name=$(echo "$branch" | tr '/' '-') 
            settings_file="${safe_branch_name}-settings.json"

            if [ -s "$settings_file" ]; then
              echo "Uploading settings for branch: $branch"
              curl --fail -X POST \
                -H "Authorization: $AUTHORIZATION" \
                -H "Content-Type: application/json" \
                -d @"$settings_file" \
                "https://api-testing.liquidbounce.net/api/v1/client/$branch/settings/sync" \
                && echo "Settings successfully uploaded for branch: $branch" \
                || (echo "Failed to upload settings for branch: $branch" && exit 1)
            else
              echo "No settings to upload for branch: $branch"
            fi
          }

          find "LiquidBounce/settings" -mindepth 1 -maxdepth 1 -type d | while read -r dir; do
            branch=$(basename "$dir")
            process_directory "$branch"
            upload_settings "$branch"
          done

      - name: Upload JSON Files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: settings-payloads
          path: '*-settings.json'
